config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get  '/fun_page' => 'static_pages#fun_page'
  get  '/googleef3be4909b8502a4.html', to: redirect('/public/googleef3be4909b8502a4.html')
  
  resources :projects
  resource :messages do
    collection do
      post 'reply'
      get 'reply'
    end
  end

  if Rails.env.production?
    offline = Rack::Offline.configure :cache_interval => 120 do
      cache ActionController::Base.helpers.asset_path("application.css")
      cache ActionController::Base.helpers.asset_path("application.js")
      # cache other assets
      network "/"
    end
    get "/application.manifest" => offline
  end
end

app/models/project.rb
class  Project < ActiveRecord::Base
  validates_presence_of :name,
                        :description,
                        :purpose,
                        :technology,
                        :url

  # TODO: "Figure out how to reset test data base after tests so there is not more than one unique name in the data base when testing for name uniqueness. Test database builds to have LOTS of examples."
  # validates_uniqueness_of :name

  validates :name, length: { maximum: 50 }

  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar,
  styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  },
  default_url:  "https://#{Rails.application.secrets.s3_host_name}/#{Rails.application.secrets.s3_bucket_name}/images/:style/missing.png",
  storage: :s3,
  s3_host_name:      "s3-us-west-2.amazonaws.com",
  access_key_id:     Rails.application.secrets.aws_access_key_id,
  secret_access_key: Rails.application.secrets.aws_secret_access_key


  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_action :find_all_projects
  before_action :prepare_meta_tags, if: "request.get?"

  def prepare_meta_tags(options={})
    site_name   = "Dillon Downey's website"
    title       = [controller_name, action_name].join(" ")
    description = "This website is a portfolio for showcasing my web development skills and personal endevours."
    image       = options[:image] || "../assets/images/Dillon-900x600.jpg"
    current_url = request.url

    defaults = {
      site:        site_name,
      title:       title,
      image:       image,
      description: description,
      keywords:    %w[web software development app junior  developer front-end back-end Full-stack ],
      twitter: {
        card: 'summary',
        site: '@downeydillon1',
        title: title,
        description: description,
        image: image
      },
     og: {
        url: current_url,
        site_name: site_name,
        title: title,
        image: image,
        description: description,
        type: 'website'
      }
    }
    options.reverse_merge!(defaults)
    set_meta_tags options
  end
end

app/controllers/messages_controller.rb
require 'twilio-ruby'

class MessagesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  # If using Devise gem for authorization
  #skip_before_filter :authenticate_user!, :only => "reply"

  def new
    boot_twilio
  end

  def reply
    body = params[:body]
    from_phone_number = params[:phone]

    boot_twilio
    @twilio_number = Rails.application.secrets.twilio_number

    @client.account.messages.create({
      from: @twilio_number,
      # from: '+15005550006', # Twilio test number
      to:   '18056805036',
      body: "#{body}",
    })
    redirect_to root_path
  end


  private

    def boot_twilio
      account_sid = Rails.application.secrets.twilio_sid
      auth_token  = Rails.application.secrets.twilio_token
      @client = Twilio::REST::Client.new account_sid, auth_token
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
    @project  = Project.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = "Project saved successfully."
      redirect_to @project
    else
      flash[:error] = "ERROR: Project did NOT save."
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:success] = "#{@project.name} updated successfully."
      redirect_to @project
    else
      flash[:error] = "ERROR: #{@project.name} did NOT update."
      render :edit
    end
  end

  def destroy
    if @project.delete
      flash[:success] = "#{@project.name} deleted successfully."
      redirect_to projects_path
    else
      flash[:error] = "ERROR: #{@project.name} did NOT delete."
      redirect_to root_path
    end
  end

  private
    def project_params
      params.require(:project).permit(
        :name,
        :description,
        :purpose,
        :technology,
        :url,
        :avatar
      )
    end

    def find_project
      @project = Project.find(params[:id])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @projects = Project.all
    @description = "Find out more about me and projects I have been working on.
    Open to junior web development opportunities."
  end

  def fun_page
    @description = "A playground page for displaying mini components of stuff
    I am learning about."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis
  def base_title
    "Dillon Downey | Index"
  end

  def full_title(page_title)
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path 'favicon/apple-touch-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path 'favicon/apple-touch-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path 'favicon/apple-touch-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path 'favicon/apple-touch-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path 'favicon/apple-touch-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path 'favicon/apple-touch-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path 'favicon/apple-touch-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path 'favicon/apple-touch-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon-180x180.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/android-chrome-192x192.png' %>" sizes="192x192">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-96x96.png' %>" sizes="96x96">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="<%= asset_path 'favicon/mstile-144x144.png' %>">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_flash_message.html.erb
<% if flash.present? %>
  <div class="alert flash_message">
      <% flash.each do |name, msg| %>
        <% if msg.is_a?(String) %>
          <%= content_tag(:div, msg, class: "alert alert_#{name} flash_#{name}") %>
        <% end %>
      <%end%>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="footerSection">
  <h2 class="sr-only">Footer</h2>
  <%= render 'shared/social_media_nav' %>
</footer>

app/views/layouts/_intro_container.html.erb
<section class="introContainer">
  <h2><span translate="no">Dillon Downey</span> - Junior Web Developer</h2>
  <div class=" introContainer__portfolioPicSection">
    <h3 class="sr-only">Portfolio picture</h3>
    <figure class="introContainer__figure" itemprop="image">
      <!-- TODO: Fix file path of image to server through S3 and Amazon cloudfront.  File path gives 403 forbidden -->
      <%# image_tag "https://DomainName.cloudfront.net/images/Dillon-500x333" %>
      <%= image_tag("",
        data: { "src" => "assets/dillon-500x333.jpg" },
        width: "500",
        height:"333",
        alt:   "Dillon Downey\'s portfolio picture",
        class: "portfolioPic") %>
      <figcaption>
        <h3>Dillon Downey</h3>
      </figcaption>
    </figure>
    <%= render 'shared/social_media_nav' %>
  </div>
  <div class="introContainer__aboutMeSection">
    <h2 class="sr-only">About Me</h2>
    <p>
      Hi, my name is
      <span itemprop="givenName" translate="no" >Dillon </span>
      <span itemprop="familyName" translate="no">Downey</span>.
      I am currently enjoying life in the beautiful Portland, Oregon area where my lovely wife and I decided to dive head first into our careers as web developers.  Prior to changing careers, I worked in customer service as a
      <span translate="no">GNC (General Nutrition Center)</span>
      Senior Store Manager.
    </p>
    <p>
      I became interested in becoming a
      <span itemprop="JobTitle">junior web developer</span>
      because I had an injury that required me to take some time off of work.  During that time, I explored web development by completing three online computerscience courses through the local community college.  This led me to
      <span itemprop="alumniof" translate="no">Dev BootCamp</span>
      in San Francisco where I immersed myself in their 19 week curriculum whichincluded SQL, algorithms, JavaScript, jQuery, Ajax, and Ruby on Rails. I alsoparticipated in a final group project that created an operating interface for aParrot AR Drone.  One of the greatest tools I walked away with is the ability toacknowledge and embrace confusion and to believe with enough effort anybody canlearn just about anything.
    </p>
    <p>
      With my new found passion for programming, I find myself obsessing over clean looking resuable code, user experience, and web performance.  I am continually looking for new technologies and best practices to further my journey to becoming an expert at my craft.  If you would like to drop me a line, I always appreciate actionable, specific, and kind
      <%= mail_to "downeydillon@gmail.com", "feedback",
        subject: "Feedback on dillondowney.herokuapp.com",
        itemprop:"email" %>.
    </p>
  </div>
</section>

app/views/layouts/_navbar.html.erb
<nav>
  <h2 class="sr-only">Main Navigation</h2>
  <div class="navContainer">
    <!-- TODO: Add brand logo -->
    <%= link_to "Home", root_path %>
    <%= render "/static_pages/table_of_contents" %>
    <ul>
      <li>
        <%= link_to "Old Blog",
          "https://downeyd27.github.io/blog/blog-index.html",
          target:"blank" %>
      </li>
      <li>
        <%= link_to "Resume",
          "https://resume.creddle.io/resume/1rktq4ubpei",
          target:"blank"  %>
      </li>
      <li>
        <%= link_to "Contact", new_messages_path %>
      </li>
      <li>
        <%= link_to "Fun Page", fun_page_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <!-- Stylesheets need to be before meta tags.  New Relic
  creates a script tag that gets inserted after meta content='IE=edge'  -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta content='IE=edge' http-equiv='X-UA-Compatible'>
  <%= display_meta_tags %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/favicon' %>
  <%= render 'layouts/shim' %>
  <!-- TODO: <title>Dillon Downey | Index</title> and <title>Dillon Downey's | Index</title> both render due to display_meta_tags method. -->
  <!-- TODO: 2 inline script blocks were found in the head between an external CSS file and another resource. To allow parallel downloading, move the inline script before the external CSS file, or after the next resource. -->
</head>
<body class="<%= controller_name %> <%= action_name %> site" itemscope itemtype="http://schema.org/Person">
  <main id="mainSection" class="siteContent">
    <header>
      <h1 class="sr-only">Dillon Downeys Website</h1>
      <%= link_to "Skip to main content", "#mainSection", class:"sr-only" %>
      <%= link_to "Skip to project section", "#projectSection", class:"sr-only" %>
      <%= link_to "Skip to footer", "#footerSection", class:"sr-only" %>
      <%= render "layouts/navbar" %>
      <%= render "layouts/flash_message" %>
    </header>
    <%= yield %>
  </main>
  <%= render 'layouts/footer.html' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, defer: :async %>
  <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCGBtVUUvwx9VDfDFE0qk1EjzAcAuo05uE&callback=initMap">
  </script>
  <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
</body>
</html>

app/views/messages/_message_form.html.erb
<%= form_tag reply_messages_path, method: :post, class:"" do %>
  <%= text_area_tag :body, "", placeholder:"Drop me a line", size: "36x12"  %>
  <%= submit_tag "Send" %>
<% end %>

app/views/messages/new.html.erb
<section class="contactContainer">  
  <h1>Contact me</h1>
  <%= render "message_form" %>
</section>

app/views/messages/reply.html.erb
<%= content_for :title do %><%= action_name %><% end %>
<h1>Contact me</h1>


<%= form_tag reply_messages_path, method: :post, class: "navbar-form navbar-left search-form" do %>
  <%= render "message_form" %>
<% end %>

app/views/partials/_canvas_section.html.erb
<section class="debug container canvas-section section col-md-12">
  <h2>Canvas Art</h2>
  <div class="debug row">
    <canvas id="myCanvas">
      Your browser does not support the canvas tag.
    </canvas>
  </div>
</section>

app/views/partials/_change_background_color_section.html.erb
<section class="debug container section col-md-4 col-md-offset-4">
  <h2 class="sr-only">Want to change the background?</h2>
  <div class="debug row">
    <form>
      <label>Select a Background Color:</label>
      <input type="color" id="colorChooser" list="colors">
      <datalist id="colors">
        <option label="blue"  value="#0000FF"></option>
        <option label="green" value="#00FF00"></option>
        <option label="red"   value="#FF0000"></option>
        <option label="white" value="#FFFFFF"></option>
      </datalist>
    </form>
  </div>
</section>

app/views/partials/_just_for_fun_section.html.erb
<section class="debug flex">
  <h2>Just for fun!</h2>
  <canvas id="myCanvas" class="debug ">
    Your browser does not support the canvas tag.
  </canvas>
</section>

app/views/projects/_form.html.erb
<h2 class="sr-only">Project Form</h2>

<%= form_for @project, html: { role: "form" } do |f| %>
  <%= render "shared/errors", object: @project %>

    <%= f.label      :name, "Name:" %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label      :technology, "Technology:" %>
    <%= f.text_field :technology, class: "form-control" %>

    <%= f.label      :description, "Description:" %>
    <%= f.text_area  :description, class: "form-control" %>

    <%= f.label      :purpose, "Purpose:" %>
    <%= f.text_area  :purpose, class: "form-control" %>

    <%= f.label      :url, "Url:" %>
    <%= f.text_field  :url, class: "form-control" %>

    <%= f.label      :avatar, "Image Url:" %>
    <%= f.file_field :avatar, class: "form-control" %>

    <%= f.submit %>
<% end %>

app/views/projects/_projects.html.erb
<section class="projectsSection">
  <h2>Projects</h2>
  <% @projects.each do |project| %>
    <div id="project<%= project.id %>" class="projectCard">
      <h3 class="projectCard__header"><%= project.name %></h3>
      <%= link_to project.url do %>
        <%= image_tag("",
        data:   { "src" => project.avatar.url(:medium) },
        width:  "300",
        height: "300",
        alt:    "#{project.description}") %>
      <% end %>
      <span>Description: </span><p><%= project.description %></p>
      <span>Purpose:     </span><p><%= project.purpose     %></p>
      <span>Technology:  </span><p><%= project.technology  %></p>
      <span>Project Url: </span>
      <p>
        <%= link_to project.url, class:"projectCard__url" do %>
          <%= project.url %>
        <% end %>
      </p>
    </div>
  <% end %>
</section>

app/views/projects/edit.html.erb
<h1><%= @project.name %> Edit Page</h1>

<section>
  <figure class="projectSection__figure">
    <%= link_to "#{@project.url}", class:"projectSection__Link" do %>
      <%= image_tag("",
      data:   "#{@project.avatar.url}",
      width:  "300",
      height: "300",
      alt: "#{@project.description}",
      class: " projectSection__image") %>
    <% end %>
    <!-- FORM -->
    <%= render "projects/form" %>
  </figure>
  <div class=" crudLinks">
    <%= link_to "Edit Project Page", edit_project_path(@project) %>
    <%= link_to "Delete Project", project_path(@project),
      data: {
        confirm: "Are you sure you want to delete this project?",
        method: :delete
      } %>
    <%= link_to "All Projects Page", projects_path %>
    <%= link_to 'Load new Project', new_project_path %>
  </div>
</section>

app/views/projects/index.html.erb
<h1>Project Index</h1>

<%= render partial: "projects",
           locals: { projects: @projects } %>
  

app/views/projects/new.html.erb
<h1>New Project Page</h1>
<div class="projectFormContainer">
  <%= render "projects/form" %>
</div>

app/views/projects/show.html.erb
<section class="projectsSection">
  <div class="project<%= @project.id %> projectCard">
    <h3 class="projectCard__header"><%= @project.name %></h3>
    <%= link_to @project.url do %>
      <%= image_tag("",
      data:   { "src" => @project.avatar.url(:medium) },
      width:  "300",
      height: "300",
      alt:    "#{@project.description}") %>
    <% end %>
    <span>Description: </span><p><%= @project.description %></p>
    <span>Purpose:     </span><p><%= @project.purpose     %></p>
    <span>Technology:  </span><p><%= @project.technology  %></p>
    <span>Project Url: </span>
    <p>
      <%= link_to @project.url, class:"projectCard__url" do %>
      <%= @project.url %>
      <% end %>
    </p>
    <div>
      <%= link_to "Edit", edit_project_path(@project) %>
      <%= link_to "Delete",    project_path(@project),
      data: {
        confirm: "Are you sure you want to delete this project?",
        method: :delete
        } %>
        <%= link_to "Show all Projects", projects_path %>
    </div>
  </div>
</section>

app/views/resume/index.html.erb
<div class="row">
  <!-- resume -->
  <iframe class="debug col-md-offset-2 col-md-8" src="https://resume.creddle.io/embed/1rktq4ubpei" width="850" height="1100" seamless></iframe>
</div>

app/views/shared/_crud_links.html.erb
<div class="crudLinks">
  <ul class="crudLinkContainer">
    <li><%= link_to "All Projects Page", projects_path %></li>
    <li><%= link_to 'Load New Project', new_project_path %></li>
    <li><%= link_to "Edit Project Page", edit_project_path(project) %></li>
    <li>
      <%= link_to "Delete Project", project_path(project),
      data: {
        confirm: "Are you sure you want to delete this project?",
        method: :delete
      } %>
    </li>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert_error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_social_media_nav.html.erb
<div class="debug socialMediaContainer" role="navigation">
  <h4 class="sr-only">Social Media Navigation</h4>
  <%= mail_to "mailto:downeydillon@gmail.com" do %>
    <%= image_tag("",
      data: { "src" => "assets/icons/gmail-64x64.png" },
      width:"64",
      height:"64",
      alt:"Gmail link icon",
      class:"gmail-icon") %>
  <% end %>
  <%= link_to "https://github.com/downeyd27", itemprop:"url" do %>
    <%= image_tag("",
      data: { "src" => "assets/icons/github-64x64.png" },
      width:"64",
      height:"64",
      alt:"Github link icon",
      class:"github-icon") %>
  <% end %>
  <%= link_to "https://www.linkedin.com/in/dillondowney", itemprop:"url" do %>
    <%= image_tag("",
      data: { "src" => "assets/icons/linkedin-64x64.png" },
      width:"64",
      height:"64",
      alt:"Linkedin link icon",
      class:"linkedin-icon") %>
  <% end %>
</div>

app/views/static_pages/_geo_location.html.erb
<div class="geo-location-container">
  <h3>HTML5 geoLocation API in action</h3>
  <div>
    <p id ="geo-message">Click the button to see your location</p>
    <button id="get-location">Where are you?</button>
    <button id="remove-location">Remove Coordinates</button>
  </div>
  <div id="trip-meter">
    <p>
      Starting Location (lat, lon)
      <span id="starting-latitude">???</span>,
      <span id="starting-longitude">???</span>
    </p>
    <p>
      Current Location (lat, lon)
      <span id="current-latitude">???</span>,
      <span id="current-longitude">???</span>
    </p>
    <p>
      Distance travelled:
      <span id="distance-travelled">0</span>
    </p>
    <p>
      Altitude: <span id="altitude">0</span>
    </p>
  </div>
  <!-- Position display -->
  <div id="myposition"></div>

  <!-- Google Maps -->
  <div id="map" style="width:640px;height:480px"></div>
</div>

app/views/static_pages/_local_storage.html.erb
<div class="local-storage">
  <h3>HTML5 localStorage API in action</h3>
  <output id="counter"></output>

  <button id="show-local-storage">
    Show all data in localStorage
  </button>
  <output id="list"></output>

  <button id="add-item-to-local-storage">
    Add data to localStorage
  </button>
  <button id="remove-item-from-local-storage">
    Remove data from localStorage
  </button>
  <button id="clear-local-storage">
    Clear data in localStorage
  </button>
</div>

app/views/static_pages/fun_page.html.erb
<%= content_for :title do %><%= action_name %><% end %>
<div class="fun-page-container">
  <h2>Fun Page!</h2>
  <%= render "local_storage" %>
  <%= render "geo_location" %>
</div>

app/views/static_pages/index.html.erb
<%= render "/layouts/intro_container" %>
<%= render "/projects/projects" %>